services:
  - type: web
    name: trans-evals-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 8000